In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Language" : ["Python", "C++", "Java", "Javascript"],
    "Rating" : [10, 8, 7, 8]
}

df = pd.DataFrame(data)
df

     Language  Rating
0      Python      10
1         C++       8
2        Java       7
3  Javascript       8

In [4]:
df["Rating"].mean()

np.float64(8.25)

In [5]:
df.sort_values("Rating", ascending=False)

     Language  Rating
0      Python      10
1         C++       8
3  Javascript       8
2        Java       7

In [6]:
df[df["Rating"] > 7]

     Language  Rating
0      Python      10
1         C++       8
3  Javascript       8

In [7]:
df.to_csv("languages.csv")