In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

df

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78
3    David     88

In [3]:
df.columns

Index(['Name', 'Marks'], dtype='object')

In [4]:
df.shape

(4, 2)

In [5]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [6]:
df["Marks"]

0    85
1    92
2    78
3    88
Name: Marks, dtype: int64

In [8]:
df["Marks"].mean()

np.float64(85.75)

In [9]:
df["Marks"].max()

np.int64(92)

In [10]:
df["Marks"].min()

np.int64(78)

In [11]:
df[df["Marks"] > 85]

    Name  Marks
1    Bob     92
3  David     88

In [12]:
df.sort_values("Marks", ascending=False)

      Name  Marks
1      Bob     92
3    David     88
0    Alice     85
2  Charlie     78

In [13]:
df["Grade"] = ["B", "A", "C", "B"]

In [14]:
df

      Name  Marks Grade
0    Alice     85     B
1      Bob     92     A
2  Charlie     78     C
3    David     88     B

In [15]:
df.to_csv("students.csv", index=False)