In [2]:
import pandas as pd
import numpy as np

In [3]:
students = {
    "Name": ["A", "B", "C", "D", "E"],
    "Math": [90, 75, 88, 60, 95],
    "Science": [85, 70, 90, 65, 92]
}

df = pd.DataFrame(students)

df

  Name  Math  Science
0    A    90       85
1    B    75       70
2    C    88       90
3    D    60       65
4    E    95       92

In [5]:
df["Total"] = df["Math"] + df["Science"]

In [6]:
df

  Name  Math  Science  Total
0    A    90       85    175
1    B    75       70    145
2    C    88       90    178
3    D    60       65    125
4    E    95       92    187

In [9]:
df["Average"] = df["Total"] / 2

In [10]:
df

  Name  Math  Science  Total  Average
0    A    90       85    175     87.5
1    B    75       70    145     72.5
2    C    88       90    178     89.0
3    D    60       65    125     62.5
4    E    95       92    187     93.5

In [11]:
df.sort_values("Average", ascending=False)

  Name  Math  Science  Total  Average
4    E    95       92    187     93.5
2    C    88       90    178     89.0
0    A    90       85    175     87.5
1    B    75       70    145     72.5
3    D    60       65    125     62.5

In [12]:
df["Average"].mean()

np.float64(81.0)